In [1]:
import main as x

print("Hello World")

x.test()

Hello World
Start clustering


In [2]:
import numpy as np
from scipy.spatial import ConvexHull, convex_hull_plot_2d
points = np.random.rand(30, 2)   # 30 random points in 2-D
hull = ConvexHull(points)

In [9]:
hull.simplices

array([[ 3, 10],
       [ 3,  1],
       [15, 14],
       [15,  1],
       [27, 10],
       [27, 19],
       [13, 19],
       [25, 14],
       [25, 13]], dtype=int32)

In [10]:
hull.vertices

array([10,  3,  1, 15, 14, 25, 13, 19, 27], dtype=int32)

In [11]:
points

array([[0.66632769, 0.35023018],
       [0.72857368, 0.04785647],
       [0.48938816, 0.80490135],
       [0.15407634, 0.10305621],
       [0.87748449, 0.26673124],
       [0.37259226, 0.10368756],
       [0.93594387, 0.08138617],
       [0.31855286, 0.75221032],
       [0.3348498 , 0.11944986],
       [0.54969655, 0.88579793],
       [0.01511532, 0.25808717],
       [0.61570964, 0.43888495],
       [0.69914398, 0.13743103],
       [0.75831838, 0.93052038],
       [0.97880992, 0.5928332 ],
       [0.95572603, 0.06447644],
       [0.61484071, 0.52939009],
       [0.82758267, 0.55785711],
       [0.90579843, 0.59361632],
       [0.05594507, 0.85757894],
       [0.64068111, 0.88673064],
       [0.35261495, 0.79066687],
       [0.60014496, 0.36715144],
       [0.32055776, 0.19782883],
       [0.47463865, 0.41023098],
       [0.96867143, 0.86809825],
       [0.75643005, 0.60691562],
       [0.01676826, 0.65071693],
       [0.32147713, 0.47550942],
       [0.71603916, 0.32806523]])

In [14]:
hull.volume

0.7660442340295488

In [15]:
hull.area

3.3461517185729446